version: '3.8'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      - ./backend:/usr/app
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
    depends_on:
      - db
    networks:
      - app_network


  db:
    image: postgres:11.5-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - app_network


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: on-failure
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules  
    networks:
      - app_network


networks:
  app_network:


