version: '3.8'

services:
  chat-app:
    build:
      context: ./chat-app
    env_file: ./chat-app/.env
    restart: unless-stopped
    ports:
      - 7001:7001
    tty: true
    volumes: 
      - ./chat-app:/chat-app
      - /chat-app/node_modules
    command: yarn watch
    depends_on:
      - api-gateway

  api-gateway:
    build:
      context: ./api-gateway
    restart: unless-stopped
    ports:
      - 7000:7000
    tty: true
    volumes: 
      - ./api-gateway:/api-gateway
      - /api-gateway/node_modules
    command: yarn watch
    depends_on:
      - users-service
      - chat-service

  chat-service-db:
    image: mysql:5.7.20
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    volumes:
      - ./db_data/chat-service-db:/var/lib/mysql
    ports:
      - 7200:3306
  
  chat-service:
    build:
      context: ./chat-service
    restart: unless-stopped
    ports:
      - 7100:7100
    tty: true
    volumes: 
      - ./chat-service:/chat-service
      - /chat-service/node_modules
    command: yarn watch
    depends_on:
      - chat-service-db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 7300:80
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    depends_on:
      - chat-service-db
      - users-service-db

  users-service-db:
    image: mysql:5.7.20
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    volumes:
      - ./db_data/users-service-db:/var/lib/mysql
    ports:
      - 7201:3306

  users-service:
    build:
      context: ./users-service
    restart: unless-stopped
    ports:
      - 7101:7101
    tty: true
    volumes: 
      - ./users-service:/users-service
      - /users-service/node_modules
    command: sh -c "yarn db:migrate && yarn watch"
    depends_on:
      - users-service-db